# Generated by Django 5.2.1 on 2025-05-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_app", "0002_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="borrowedBy",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="isBorrowed",
            field=models.BooleanField(default=False),
        ),
    ]
