# Generated by Django 5.2.1 on 2025-05-16 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_app", "0003_book_borrowedby_book_isborrowed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="borrowedBy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
